import { NextRequest, NextResponse } from "next/server";
import { google } from "googleapis";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { auth } from "@/lib/auth";

const DASHBOARD = new URL("/dashboard/calendar", process.env.BETTER_AUTH_URL!);

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const code = searchParams.get("code");  // google has redirected the user back here with a code, and this route exchanges it for tokens, persists them, and sets up push notifications. 
  const mentorId = searchParams.get("state");
  const error = searchParams.get("error");

  //Basic Validation
  if (error || !code || !mentorId) {
    return NextResponse.redirect(`${DASHBOARD.toString()}?error=missing_params`);
  }

  //Session validation
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session || session.user.id !== mentorId) {
    return NextResponse.redirect(new URL("/login", process.env.BETTER_AUTH_URL!));
  }

  const oauth2Client = new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID,
    process.env.GOOGLE_CLIENT_SECRET,
    `${process.env.BETTER_AUTH_URL}/api/auth/google-calendar/callback`
  );

  let tokens;
  try {
    //Handle the "Single-Use code" risk
    const response = await oauth2Client.getToken(code);           //exchange the code for tokens
    tokens = response.tokens;
  } catch (tokenErr){
    console.error("Token exchange failed (likely code expired or refused:", tokenErr);
    return NextResponse.redirect(`${DASHBOARD.toString()}?error=oauth_timeout`);
  }


  const tokenExpiry = tokens.expiry_date
    ? new Date(tokens.expiry_date)
    : new Date(Date.now() + 60 * 60 * 1000);

  //Fetch existing data to preserve refresh_token, and get old channel info. 
  const { data: existing } = await supabaseAdmin
    .from("calendar_integrations")
    .select("refresh_token, channel_id, resource_id")
    .eq("mentor_id", mentorId)
    .eq("provider", "google")
    .maybeSingle();

  await supabaseAdmin.from("calendar_integrations").upsert({
    mentor_id: mentorId,
    provider: "google",
    access_token: tokens.access_token!,
    refresh_token: tokens.refresh_token ?? existing?.refresh_token ?? "",
    token_expiry: tokenExpiry.toISOString(),
    updated_at: new Date().toISOString(),
  }, { onConflict: "mentor_id,provider" });

  try {
    oauth2Client.setCredentials(tokens);
    const calendar = google.calendar({ version: "v3", auth: oauth2Client });

    //Stop the old channel if it exists
    //this prevents duplicate notifications and cleans up old resources.
    if (existing?.channel_id && existing?.resource_id) {
        try {
            await calendar.channels.stop({
                requestBody: {
                    id : existing.channel_id,
                    resourceId: existing.resource_id,
                },
            });
        } catch (stopError) {
            // We catch this but don't block—it often fails if the channel already expired
            console.log("Could not stop old channel, it may have already expired.");
        }
    }

    //Start the new channel
    const channelId = crypto.randomUUID();
    //Google's max expiration is usually 7 days (604800 seconds)
    const requestedExpiry = Date.now() + 7 * 24 * 60 * 60 * 1000;

    //tells Google when anything changes on this user’s primary calendar, POST to my webhook URL.
    const watchRes = await calendar.events.watch({
      calendarId: "primary",
      requestBody: {
        id: channelId,
        type: "web_hook",
        address: `${process.env.BETTER_AUTH_URL}/api/webhooks/google-calendar`,
        token: mentorId,   //This is passed back in headers, but verify channel_id in the webhook!
        expiration: requestedExpiry.toString(),
      },
    });

    //Capture the resourceId from the response and update the DB
    //watchRes.data contains the resourceId generated by Google
    const { resourceId, expiration } = watchRes.data;
    const finalExpiry = expiration ? new Date(parseInt(expiration)) : new Date(requestedExpiry);

    await supabaseAdmin.from("calendar_integrations").update({
      channel_id: channelId,
      resource_id: resourceId,   //Storing the Google-generated ID
      channel_expiry: finalExpiry.toISOString(),
      renew_at: new Date(Date.now() + (finalExpiry.getTime() - Date.now()) / 2).toISOString(),
    }).eq("mentor_id", mentorId).eq("provider", "google");
  } catch (watchErr){
    console.error("Webhook setup failed:", watchErr);
    // We don't redirect with error here because the tokens are already saved.
    // The user is integrated, just without push notifications.
  }

  return NextResponse.redirect(DASHBOARD);
}
